

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGOUT = 'USER_LOGOUT';


// price list:
export const GET_PRICELIST = 'GET_PRICELIST';
// contacts:
export const GET_CONTACTS = 'GET_CONTACTS';
// notifications:
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const RESET_NOTIFICATION_SEARCH = 'RESET_NOTIFICATION_SEARCH';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
// users (employees and clients):
export const GET_USERS_SHORT = 'GET_USERS_SHORT';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const USERS_LOADING = 'USERS_LOADING';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const GET_OUR_TEAM = 'GET_OUR_TEAM';  
export const TEAM_LOADING = 'TEAM_LOADING';
// pets:
export const GET_PETS = 'GET_PETS';
export const PETS_LOADING = 'PETS_LOADING';
export const UPDATE_PET = 'UPDATE_PET';
//messages:
export const GET_CLIENT_SENDERS = 'GET_CLIENT_SENDERS';
export const GET_EMPLOYEE_SENDERS = 'GET_EMPLOYEE_SENDERS';
export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const GET_COUNT_NEW_MSG = 'GET_COUNT_NEW_MSG';
export const GET_MESSAGES = 'GET_MESSAGES';

// appointments:
export const GET_DOCTOR_APPOINTMENTS = 'GET_DOCTOR_APPOINTMENTS';
export const APPOINTMENTS_LOADING = 'APPOINTMENTS_LOADING';
export const SET_APPOINTMENTS_ADD_SUCCESS = 'SET_APPOINTMENTS_ADD_SUCCESS';
// clients
export const GET_CLIENT_APPOINTMENTS = 'GET_CLIENT_APPOINTMENTS';
// appointments  MODALS:
export const APPOINTMENTS_MODAL_LOADING = 'APPOINTMENTS_MODAL_LOADING';
export const SET_APPOINTMENTS_MODAL_ERROR = 'SET_APPOINTMENTS_MODAL_ERROR';
export const GET_DETAILS_APPOINTMENT = 'GET_DETAILS_APPOINTMENT';
export const GET_REGISTER_APPOINTMENT = 'GET_REGISTER_APPOINTMENT';
//admin
export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
export const ADMIN_LOADING = 'ADMIN_LOADING';
export const GET_PERMISSIONS = 'GET_PERMISSIONS';
export const SET_NEW_PERMISSION = 'SET_NEW_PERMISSION';
export const CLEAN_PERMISSIONS_BY_ROLES = 'CLEAN_PERMISSIONS_BY_ROLES';
